### ISSUE TITLE
How is a "category" decided on Rarible.com, does it use the protocol?

### ISSUE THREAD

**Issue by skogard** [rarible/protocol-issues#6]
How is the category decided? For example this one has an "art" category. I know that the protocol doesn't have such a thing as "category", is this automatically classified by the Rarible backend? 

How does one make sure their NFT gets assigned a category when minting using the protocol?

<img width="347" alt="xasd" src="https://user-images.githubusercontent.com/76128958/129389818-04fabcd3-619b-48b3-96e4-d5e5e463e51e.png">

**Comment by fallengravity** [comment]
Right now most things are marked as art, and to have the category changed you will need to contact the support team (We have a special form for this - I will update the comment when I have access to my laptop to grab the link). 

I believe it is in our backlog to allow users to select a category when minting on Rarible.com. As for the protocols side, I'll leave that for one of the Protocol devs to address.

**Comment by skogard** [comment]
> Right now most things are marked as art

Does this mean it's automatically assigned? Or somehow manually tagged by the user? I couldn't find a way to do it manually on Rarible.com UI.

> I believe it is in our backlog to allow users to select a category when minting on Rarible.com. As for the protocols side, I'll leave that for one of the Protocol devs to address.

If the category is not yet determined we could even think about creating a metadata standard that automatically categorizes tokens so that we could do this natively with the protocol without changing the protocol at all. But first I guess we need to understand how this actually works today.

Just FYI some people feel disadvantaged for using the protocol to mint (vs. minting on the website) because their tokens don't get assigned a category and therefore don't get any exposure under the categories.

**Comment by fallengravity** [comment]
Yup, automatically assigned right now on Rarible.com, can be assigned to other categories manually, as promised the link to request additional categorization: https://airtable.com/shrtGxlk0Ayy8UxOr

**Comment by skogard** [comment]
Thanks. If this is the case, I am guessing this is a bug in the Rarible backend (not being able to auto-categorize NFTs submitted through the protocol), and should be reported elsewhere?
