### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by eduardstal** [rarible/protocol-issues#85]
### Discussed in https://github.com/rarible/protocol-issues/discussions/77

<div type='discussions-op-text'>

<sup>Originally posted by **jsmellz** September  8, 2021</sup>
Pretty sure this should be aggregateNftPurchaseByCollection. 
<img width="536" alt="Screen Shot 2021-09-08 at 1 01 59 PM" src="https://user-images.githubusercontent.com/24348787/132561132-234c15b9-c85a-487f-94a6-facfb3749070.png">
</div>

**Comment by evgenynacu** [comment]
Fixed in https://github.com/rarible/ethereum-indexer/pull/46
