### ISSUE TITLE
Gnosis Compatible EIP1271

### ISSUE THREAD

**Issue by ipatka** [rarible/protocol-issues#87]
# Context

We updated the DAO eip1271 interface to match how Gnosis has implemented it. However there is now an incompatabilty with the rarible API. 

Rarible expects the EIP1271 signature to be 132 chars long (like 0xabc....def).

But Gnosis requires that the DAO's signature is a 0 length bytes array 0x. 

## Request
Could Rarible update the API so that "0x" signatures are not rejected by the schema validator? They will resolve the proper magic value on the isValidSignature call using the msg hash

Link to `isValidSignature` in Gnosis contracts: https://github.com/gnosis/safe-contracts/blob/34c87b783dfd04ff09ef7c358c3182c3c151e086/contracts/handler/CompatibilityFallbackHandler.sol#L32

Example request body to Rarible orders API that we would like to see succeed:

```
{
    "type": "RARIBLE_V2",
    "maker": "0x744222844bFeCC77156297a6427B5876A6769e19",
    "make": {
        "assetType": {
            "assetClass": "ERC721",
            "contract": "0xcfa14f6DC737b8f9e0fC39f05Bf3d903aC5D4575",
            "tokenId": 1
        },
        "value": "1"
    },
    "take": {
        "assetType": {
            "assetClass": "ETH"
        },
        "value": "1000000000000000000"
    },
    "data": {
        "dataType": "RARIBLE_V2_DATA_V1",
        "payouts": [],
        "originFees": []
    },
    "salt": "5422",
    "signature": "0x" // NOTE - 0 length signature
}
```

**Comment by evgenynacu** [comment]
@ipatka could you give me full request you are trying to send? Maybe curl?

**Comment by evgenynacu** [comment]
@ipatka I fixed this in the library
when next version is deployed on our envs, this will issues should be fixed
