### ISSUE TITLE
Collection is not indexed on the protocol

### ISSUE THREAD

**Issue by evgenynacu** [rarible/protocol-issues#93]
https://discord.com/channels/846402262443491328/887455535610343454/887793079044698152

**Comment by evgenynacu** [comment]
@sanufriev could you close the issue when it's reindexed?

**Comment by sanufriev** [comment]
@evgenynacu I will write feedback and close this issue

**Comment by bruck93** [comment]
@evgenynacu Adam Bomb Squad is not indexed

**Comment by evgenynacu** [comment]
@sanufriev pls, see https://github.com/rarible/protocol-issues/issues/93#issuecomment-921057745

**Comment by bruck93** [comment]
Cool Cats collection still have issue @evgenynacu / @sanufriev 

This asset is not available:
https://rarible.com/token/0x1a92f7381b9f03921564a437210bb9396471050c:7688?tab=details

**Comment by evgenynacu** [comment]
@sanufriev one more: "CryptoDads not indexed at all"

**Comment by bruck93** [comment]
@sanufriev : https://opensea.io/collection/galacticapes

Keep seeing different project not indexed properly

**Comment by bruck93** [comment]
Another user got issue there: https://opensea.io/collection/world-of-women-nft

**Comment by sanufriev** [comment]
> Another user got issue there: https://opensea.io/collection/world-of-women-nft

Hello, could you please point out the concrete issue with this collection?

**Comment by sanufriev** [comment]
> Also this one: https://opensea.io/collection/uwucrew

And please,  point out the concrete issue with this collection too

**Comment by sanufriev** [comment]
> Cool Cats collection still have issue @evgenynacu / @sanufriev
> 
> This asset is not available: https://rarible.com/token/0x1a92f7381b9f03921564a437210bb9396471050c:7688?tab=details

We reindexed this collection, so all items must be available

**Comment by bruck93** [comment]
This metahero is missing: https://rarible.com/token/0xfb10b1717c92e9cc2d634080c3c337808408d9e1:23?tab=details

**Comment by sanufriev** [comment]
> This metahero is missing: https://rarible.com/token/0xfb10b1717c92e9cc2d634080c3c337808408d9e1:23?tab=details

Hello, thank you, we fixed the issue with this collection

**Comment by evgenynacu** [comment]
@bruck93 is everything working as expected? Closing this.
If not working, pls, reopen

**Comment by bruck93** [comment]
@evgenynacu / @sanufriev thanks for your support.

We saw also this asset ( indexed on OS: https://opensea.io/assets/0xa7ee407497b2aeb43580cabe2b04026b5419d1dc/2152 ) not indexed properly on Rarible ( https://rarible.com/token/0xa7ee407497b2aeb43580cabe2b04026b5419d1dc:2152?tab=details )

There are other assets from the same collection not yet handled

**Comment by evgenynacu** [comment]
@bruck93 pls reopen the issue if you find new examples of this

**Comment by sanufriev** [comment]
> This collection is missing: https://opensea.io/collection/entities-multipass
> 
> @evgenynacu / @sanufriev

I think it is on Rarible 
https://rarible.com/collection/0x22ca6c273d2d8be5bb11e762741efd67acdd3315
Is any thing wrong with it?

**Comment by evgenynacu** [comment]
Closing this. Reopen if anything's not right
