### ISSUE TITLE
Collection 0xf7a6e15dfd5cdd9ef12711bd757a9b6021abf643 not indexed

### ISSUE THREAD

**Issue by evgenynacu** [rarible/protocol-issues#96]
### Discussed in https://github.com/rarible/protocol-issues/discussions/60

<div type='discussions-op-text'>

<sup>Originally posted by **alex-zmo** August 28, 2021</sup>
On opensea, when querying for assets by owner address, it paginates and shows all assets

with rarible API, some assets are missing 

example:
owner: 0xdf0635793e91d4f8e7426dbd9ed08471186f428d
contractAddress : 0xf7a6e15dfd5cdd9ef12711bd757a9b6021abf643</div>

**Comment by sanufriev** [comment]
Hello. token assets are now present in Protocol-Api
https://ethereum-api.rarible.org/v0.1/nft/items/byCollection?collection=0xf7a6e15dfd5cdd9ef12711bd757a9b6021abf643

If you have other example of tokens are missing, please welcome, now we have tool to solve such problems very quickly
